/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dashboard;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import database.koneksi;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import com.lowagie.text.Document;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import database.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.util.logging.Level;
import java.util.logging.Logger;

import database.koneksi;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdul Latip Muhyi
 */
public class kelolaBarangKeluar extends javax.swing.JInternalFrame {

    /**
     * Creates new form kelolaBarangKeluar
     */
    public kelolaBarangKeluar() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    koneksi k = new koneksi();
    Connection con = k.connection;
    
    PreparedStatement ps = null;
    ResultSet rs = null;
    Object set;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfkodeBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfHargaJual = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelListBarang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfNoResi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQty = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tfKandunganNikotin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel2.setText("Kode Barang");

        tfkodeBarang.setBackground(new java.awt.Color(204, 153, 0));
        tfkodeBarang.setForeground(new java.awt.Color(255, 255, 255));
        tfkodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkodeBarangActionPerformed(evt);
            }
        });
        tfkodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfkodeBarangKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        tfNamaBarang.setEditable(false);
        tfNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaBarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel6.setText("Harga");

        tfHargaJual.setEditable(false);
        tfHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaJualActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel13.setText("QTY");

        jLabel19.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel19.setText("Alamat Tujuan");

        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel17.setText("Sub Total");

        tfSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubTotalActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(102, 153, 255));
        btnTambah.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(102, 204, 0));
        btnBatal.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(153, 153, 153));
        btnCetak.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHapus.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete_trash.png"))); // NOI18N
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        tabelListBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Kandungan Nikotin", "QTY", "Sub Total", "Alamat Tujuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelListBarang);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kelola Barang Keluar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfNoResi.setText("100000001");
        tfNoResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoResiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel4.setText("Nomer Resi");

        tfQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfQtyStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel5.setText("Kandungan Nikotin");

        tfKandunganNikotin.setEditable(false);
        tfKandunganNikotin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKandunganNikotinActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel18.setText("Total");

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfkodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(tfNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(tfNoResi, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(tfKandunganNikotin, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonHapus))
                                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1158, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfkodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel17))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(tfKandunganNikotin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(5, 5, 5)
                                                .addComponent(tfHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(96, 96, 96))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(116, 116, 116)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(5, 5, 5)
                                .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void show_barang_inJtable(){
        
//        ArrayList<barang> list = getBarangList();
//        
//        DefaultTableModel model = (DefaultTableModel)jTableBarangMasuk.getModel();
//        
//        Object[] row = new Object[8];
//        
//        for(int i=0; i < list.size(); i++){
//            row[0] = list.get(i).getKodeBarang();
//            row[1] = list.get(i).getNamaBarang();
//            row[2] = list.get(i).getTypeBarang();
//            row[3] = list.get(i).getKandunganNikotin();
//            row[4] = list.get(i).getHargaJual();
//            row[5] = list.get(i).getHargaBeli();
//            row[6] = list.get(i).getStok();
//            row[7] = list.get(i).getSuplier();
//            
//            model.addRow(row);
//        }       
    }
    
    public void executeSQLQuery(String query, String pesan)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
               
               //refresh jtable data
//               DefaultTableModel model = (DefaultTableModel)jTableBarangMasuk.getModel();
//               model.setRowCount(0);
//               show_barang_inJtable();
               
               JOptionPane.showMessageDialog(null, "Data " + pesan + " Succefully");
           }
           else{
               JOptionPane.showMessageDialog(null, "Data Not " + pesan);           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    private void tfNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaBarangActionPerformed

    private void tfHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaJualActionPerformed

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void tfSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubTotalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String tanggal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        
        
        
        int qty = Integer.parseInt(tfQty.getValue().toString());
        int harga = Integer.parseInt(tfHargaJual.getText());
        
        int subTotal = qty * harga;
        
        tfSubTotal.setText(String.valueOf(subTotal));
        if(tfkodeBarang.getText().trim().equals("") ){
             JOptionPane.showMessageDialog(this, "Tidak Dapat Ditambahkan, Silahkan Masukan Kode Barang","Pesan Error", 
                       JOptionPane.ERROR_MESSAGE);             
        }else{
            DefaultTableModel model = new DefaultTableModel();

            model = (DefaultTableModel)tabelListBarang.getModel();

            model.addRow(new Object[]{

//                tfNoResi.getText(),
                tfkodeBarang.getText(),
                tfNamaBarang.getText(),
                tfHargaJual.getText(),
                tfKandunganNikotin.getText(),
                tfQty.getValue().toString(),
                tfSubTotal.getText(),
                tfAlamat.getText()

            });

            int total=0;
            for(int i=0; i<tabelListBarang.getRowCount(); i++){

                total = total + Integer.parseInt(tabelListBarang.getValueAt(i, 5).toString());

            }

            tfTotal.setText(Integer.toString(total));

            tfkodeBarang.setText("");
            tfNamaBarang.setText("");
            tfHargaJual.setText("");
            tfKandunganNikotin.setText("");
            tfSubTotal.setText("");
            tfAlamat.setText("");
            tfkodeBarang.requestFocus();
            
            int idPengguna=101;
        
        String query = "INSERT INTO `penjualan_header`(`no_resi`,`kode_barang`, `nama_barang`, `kandungan_nikotin`, `harga_jual`, `qty`, `sub_total`, `alamat`, `total`,`id_pengguna`) "
        + "VALUES ('"+tfNoResi.getText()+"', '"+tfkodeBarang.getText()+"', '"+tfNamaBarang.getText()+"', '"+tfKandunganNikotin.getText()+"','"+tfHargaJual.getText()+"','"+tfQty.getValue()+"','"+Integer.parseInt(tfSubTotal.getText())+"','"+tfAlamat.getText()+"','"+Integer.parseInt(tfTotal.getText())+"','"+idPengguna+"')";

        executeSQLQuery(query, "Inserted");
        }
        
    }//GEN-LAST:event_btnTambahActionPerformed

    public void simpanTransaksi(String query)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
                                   
                int jawab;

                jawab = JOptionPane.showOptionDialog(null, "Cetak Faktur Penjualan?", "", 
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

                if(jawab == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(null, "Cetak Faktur !");
                }               
           }
           else{
               JOptionPane.showMessageDialog(null, "Transaksi tidak dapat disimpan");           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabelListBarang.getModel();
        model.setRowCount(0);  
        
        tfTotal.setText("0");
    }//GEN-LAST:event_btnBatalActionPerformed

    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
//        String tanggal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
////        System.out.println(tanggal);
//        
//        int noResi = Integer.parseInt(tfNoResi.getText());
//        int kodeBarang = Integer.parseInt(tfKodeBarang.getText());
//        String namaBarang = tfNamaBarang.getText();
//        int kandunganNikotin = Integer.parseInt(tfKandunganNikotin.getText());
////        int typeBarang = Integer.parseInt((String)cbTypeBarang.getSelectedItem());
//        double hargaJual = Double.parseDouble(tfHargaJual.getText());
//        double subTotal = Double.parseDouble(tfSubTotal.getText());
////        int qty = Integer.parseInt(tfQty.getText());
//        String alamat = tfAlamat.getText();
//        int total = Integer.getInteger(tfTotal.getText());
//        int id_pengguna=101;
//        
//        
//        String query = "INSERT INTO `penjualan_header`(`no_resi`, `kode_barang`, `nama_barang`, `kandungan_nikotin`, `harga_jual`, `sub_total`, `alamat`, `total`, `id_pengguna`,`tanggal`) "
//                + "VALUES ('"+noResi+"','"+kodeBarang+"','"+namaBarang+"','"+kandunganNikotin+"','"+hargaJual+"','"+subTotal+"','"+alamat+"','"+total+"','"+id_pengguna+"','"+tanggal+"')";
//        
//        simpanTransaksi(query);

        Document doc = new Document();

        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if(saveFile != null){
//                saveFile = new File(saveFile.toString()+".pdf");
                PdfWriter.getInstance(doc, new FileOutputStream(new File(saveFile.toString()+".pdf")));

                doc.open();

                PdfPTable tabel = new PdfPTable(7);

                tabel.addCell("Nomor Resi");
                tabel.addCell("Kode Barang");
                tabel.addCell("Nama Barang");
                tabel.addCell("Kandungan NIkotin");
                tabel.addCell("Harga");
                tabel.addCell("QTY");
                tabel.addCell("Sub Total");
                tabel.addCell("Alamat");
                tabel.addCell("Total");
                
                for(int a=0 ; a<tabelListBarang.getRowCount(); a++){
                    String noResi = tabelListBarang.getValueAt(a, 0).toString();
                    String kode = tabelListBarang.getValueAt(a, 1).toString();
                    String nama = tabelListBarang.getValueAt(a, 2).toString();
                    String nikotin = tabelListBarang.getValueAt(a, 3).toString();
                    String harga = tabelListBarang.getValueAt(a, 4).toString();
                    String qty = tabelListBarang.getValueAt(a, 5).toString();
                    String sTotal = tabelListBarang.getValueAt(a, 6).toString();
                    String alamat = tabelListBarang.getValueAt(a, 7).toString();
                    String total = tabelListBarang.getValueAt(a, 8).toString();

                    tabel.addCell(noResi);
                    tabel.addCell(kode);
                    tabel.addCell(nama);
                    tabel.addCell(nikotin);
                    tabel.addCell(harga);
                    tabel.addCell(qty);
                    tabel.addCell(sTotal);
                    tabel.addCell(alamat);
                    tabel.addCell(total);
                }
                doc.add(tabel);

                JOptionPane.showMessageDialog(null, "DOWNLOAD SUKSES", "DOWNLOAD PDF", JOptionPane.PLAIN_MESSAGE);
                openFile(saveFile.toString()+".pdf");
//                openFile(saveFile.toString());
            }else{
                JOptionPane.showMessageDialog(null,"SILAHKAN ISI NAMA FILE");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(kelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(kelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        doc.close();
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabelListBarang.getModel();
        
        if(tabelListBarang.getSelectedRow() == -1){
            if(tabelListBarang.getSelectedRow() == 0){
                JOptionPane.showMessageDialog(this, "List Barang Kosong Tidak Dapat Dihapus","Pesan Error", 
                       JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Barang Yang Akan Dihapus","Pesan Error", 
                       JOptionPane.ERROR_MESSAGE);            
            }
        }
        else{
            //hapus data pada list barang
            model.removeRow(tabelListBarang.getSelectedRow());
            
            //ubah total pembelian
            int total=0;
            for(int i=0; i<tabelListBarang.getRowCount(); i++){

                total = total + Integer.parseInt(tabelListBarang.getValueAt(i, 5).toString());

            }

            tfTotal.setText(Integer.toString(total));
            
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void tfkodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkodeBarangActionPerformed

    private void tfNoResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoResiActionPerformed

    private void tfKandunganNikotinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKandunganNikotinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKandunganNikotinActionPerformed

    private void tfkodeBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfkodeBarangKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            String kodeBarang = tfkodeBarang.getText();
                                      
            try {
                
                String sql = "SELECT  * FROM barang WHERE kode_barang = ?";
                
                ps = con.prepareStatement(sql);
                ps.setString(1, kodeBarang);
                
                rs = ps.executeQuery();
                
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "Barang Tidak Tersedia");
                }else{
                    String namaBarang = rs.getString("nama_barang");
                    String harga = rs.getString("harga_jual");
                    String kandunganNikotin = rs.getString("kandungan_nikotin");
                    
                    tfNamaBarang.setText(namaBarang);
                    tfHargaJual.setText(harga);
                    tfKandunganNikotin.setText(kandunganNikotin);
                }
                               
            }  catch (SQLException ex) {
                Logger.getLogger(kelolaBarangKeluar.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_tfkodeBarangKeyPressed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    private void tfQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfQtyStateChanged
                int qty = Integer.parseInt(tfQty.getValue().toString());
                int harga = Integer.parseInt(tfHargaJual.getText());
        
                int subTotal = qty * harga;
        
                tfSubTotal.setText(String.valueOf(subTotal));
    }//GEN-LAST:event_tfQtyStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelListBarang;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfKandunganNikotin;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNoResi;
    private javax.swing.JSpinner tfQty;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfkodeBarang;
    // End of variables declaration//GEN-END:variables
}
