/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dashboard;

import database.koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Abdul Latip Muhyi
 */
public class kelolaBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form kelolaBarang
     */
    public kelolaBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKelolaBarang = new javax.swing.JPanel();
        jPanelKwlolaBarangKeluar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelKelolaBarangMasuk = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JDesktopPane();

        jPanelKelolaBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelKwlolaBarangKeluar.setBackground(new java.awt.Color(255, 153, 102));
        jPanelKwlolaBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKwlolaBarangKeluarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-making_notes.png"))); // NOI18N
        jLabel7.setText("Kelola Barang Keluar");

        javax.swing.GroupLayout jPanelKwlolaBarangKeluarLayout = new javax.swing.GroupLayout(jPanelKwlolaBarangKeluar);
        jPanelKwlolaBarangKeluar.setLayout(jPanelKwlolaBarangKeluarLayout);
        jPanelKwlolaBarangKeluarLayout.setHorizontalGroup(
            jPanelKwlolaBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKwlolaBarangKeluarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelKwlolaBarangKeluarLayout.setVerticalGroup(
            jPanelKwlolaBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKwlolaBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelKelolaBarang.add(jPanelKwlolaBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanelKelolaBarangMasuk.setBackground(new java.awt.Color(102, 153, 255));
        jPanelKelolaBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKelolaBarangMasukMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-making_notes.png"))); // NOI18N
        jLabel14.setText("Kelola Barang Masuk");

        javax.swing.GroupLayout jPanelKelolaBarangMasukLayout = new javax.swing.GroupLayout(jPanelKelolaBarangMasuk);
        jPanelKelolaBarangMasuk.setLayout(jPanelKelolaBarangMasukLayout);
        jPanelKelolaBarangMasukLayout.setHorizontalGroup(
            jPanelKelolaBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKelolaBarangMasukLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelKelolaBarangMasukLayout.setVerticalGroup(
            jPanelKelolaBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKelolaBarangMasukLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanelKelolaBarang.add(jPanelKelolaBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jPanelKelolaBarang.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1360, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKelolaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelKelolaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelKelolaBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKelolaBarangMasukMouseClicked
        // TODO add your handling code here:
        kelolaBarangMasuk KBM = new kelolaBarangMasuk();
        mainPanel.removeAll();
        mainPanel.add(KBM).setVisible(true);
    }//GEN-LAST:event_jPanelKelolaBarangMasukMouseClicked

    private void jPanelKwlolaBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKwlolaBarangKeluarMouseClicked
        // TODO add your handling code here:
        kelolaBarangKeluar KBK = new kelolaBarangKeluar();
        mainPanel.removeAll();
        mainPanel.add(KBK).setVisible(true);
    }//GEN-LAST:event_jPanelKwlolaBarangKeluarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelKelolaBarang;
    private javax.swing.JPanel jPanelKelolaBarangMasuk;
    private javax.swing.JPanel jPanelKwlolaBarangKeluar;
    private javax.swing.JDesktopPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
