/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dashboard;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import database.koneksi;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdul Latip Muhyi
 */
public class mastrerBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form mastrerBarang
     */
    public mastrerBarang() {
        initComponents();
        
        show_barang_inJtable();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKodeBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNamaBarang = new javax.swing.JTextField();
        jLabelTypeBarang = new javax.swing.JLabel();
        cbTypeBarang = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldKandunganNikotin = new javax.swing.JTextField();
        jButtonTambah1 = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus1 = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jTextFieldSuplier = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jTextFieldHargaJual = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHargaBeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarangMasuk = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Master Barang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel2.setText("Kode Barang");

        jTextFieldKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeBarangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        jTextFieldNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaBarangActionPerformed(evt);
            }
        });

        jLabelTypeBarang.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabelTypeBarang.setText("Type Barang ( Juice / Creame )");

        cbTypeBarang.setFont(new java.awt.Font("Swis721 Cn BT", 0, 11)); // NOI18N
        cbTypeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Juice", "2 Cream" }));

        jLabel18.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel18.setText("Kandungan Nikotin ( mm )");

        jTextFieldKandunganNikotin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKandunganNikotinActionPerformed(evt);
            }
        });

        jButtonTambah1.setBackground(new java.awt.Color(102, 153, 255));
        jButtonTambah1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N
        jButtonTambah1.setText("Tambah");
        jButtonTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambah1ActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(102, 204, 0));
        jButtonEdit.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-making_notes.png"))); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonHapus1.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHapus1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete_trash.png"))); // NOI18N
        jButtonHapus1.setText("Hapus");
        jButtonHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapus1ActionPerformed(evt);
            }
        });

        jButtonCetak.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCetak.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print.png"))); // NOI18N
        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });

        jTextFieldSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSuplierActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel19.setText("Suplier ( PT )");

        jTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtyActionPerformed(evt);
            }
        });

        jTextFieldHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaJualActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel13.setText("QTY");

        jLabel6.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel6.setText("Harga Jual");

        jTextFieldHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaBeliActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel5.setText("Harga Beli");

        jTableBarangMasuk.setFont(new java.awt.Font("Swis721 Cn BT", 0, 11)); // NOI18N
        jTableBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kandungan Nikotin", "Type Barang", "Harga Beli", "Harga Jual", "QTY", "Suplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBarangMasuk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldKandunganNikotin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTambah1)
                                .addGap(7, 7, 7)
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabelTypeBarang))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel13)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKandunganNikotin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    koneksi k = new koneksi();
    Connection con = k.connection;
    
    public ArrayList<barang> getBarangList()
    {
       ArrayList<barang> barangList = new ArrayList<barang>();
       
       String query = "SELECT * FROM barang";
       
       Statement st;
       ResultSet rs;
       
       try{
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           barang Barang;           
           while(rs.next()){
               Barang = new barang(rs.getInt("kode_barang"),rs.getString("nama_barang"), 
                       rs.getInt("kandungan_nikotin"), rs.getInt("id_type"), 
                       rs.getDouble("harga_jual"), rs.getDouble("harga_beli"), rs.getInt("stok"), rs.getString("suplier"), rs.getString("tanggal"));
               barangList.add(Barang);
           }        
       }catch(Exception e){
           e.printStackTrace();
       }       
       return barangList;
    }
    
    public void show_barang_inJtable(){
        
        ArrayList<barang> list = getBarangList();
        
        DefaultTableModel model = (DefaultTableModel)jTableBarangMasuk.getModel();
        
        Object[] row = new Object[8];
        
        for(int i=0; i < list.size(); i++){
            row[0] = list.get(i).getKodeBarang();
            row[1] = list.get(i).getNamaBarang();
            row[2] = list.get(i).getTypeBarang();
            row[3] = list.get(i).getKandunganNikotin();
            row[4] = list.get(i).getHargaJual();
            row[5] = list.get(i).getHargaBeli();
            row[6] = list.get(i).getStok();
            row[7] = list.get(i).getSuplier();
            
            model.addRow(row);
        }       
    }
    
    public void executeSQLQuery(String query, String pesan)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
               
               //refresh jtable data
               DefaultTableModel model = (DefaultTableModel)jTableBarangMasuk.getModel();
               model.setRowCount(0);
               show_barang_inJtable();
               
               JOptionPane.showMessageDialog(null, "Data " + pesan + " Succefully");
           }
           else{
               JOptionPane.showMessageDialog(null, "Data Not " + pesan);           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    public void simpanTransaksi(String query)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
                                   
                int jawab;

                jawab = JOptionPane.showOptionDialog(null, "Cetak Faktur Penjualan?", "", 
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

                if(jawab == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(null, "Cetak Faktur !");
                }               
           }
           else{
               JOptionPane.showMessageDialog(null, "Transaksi tidak dapat disimpan");           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    private void jTextFieldKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeBarangActionPerformed

    private void jTextFieldNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaBarangActionPerformed

    private void jTextFieldKandunganNikotinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKandunganNikotinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKandunganNikotinActionPerformed

    private void jButtonTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambah1ActionPerformed
        String query = "INSERT INTO `barang`(`kode_barang`, `nama_barang`, `kandungan_nikotin`, `id_type`, `harga_jual`, `harga_beli`, `stok`, `suplier`) "
        + "VALUES ('"+jTextFieldKodeBarang.getText()+"','"+jTextFieldNamaBarang.getText()+"', '"+jTextFieldKandunganNikotin.getText()+"','"+(cbTypeBarang.getSelectedIndex()+1)+"', '"+jTextFieldHargaJual.getText()+"','"+jTextFieldHargaBeli.getText()+"','"+jTextFieldQty.getText()+"','"+jTextFieldSuplier.getText()+"')";

        executeSQLQuery(query, "Inserted");
    }//GEN-LAST:event_jButtonTambah1ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String query = "UPDATE `barang` SET `nama_barang`='"+jTextFieldNamaBarang.getText()+"',"
        + "`kandungan_nikotin`='"+jTextFieldKandunganNikotin.getText()+"',"
        + "`id_type`='"+(cbTypeBarang.getSelectedIndex()+1)+"',"
        + "`harga_jual`='"+jTextFieldHargaJual.getText()+"',"
        + "`harga_beli`='"+jTextFieldHargaBeli.getText()+"',"
        + "`stok`='"+jTextFieldQty.getText()+"',"
        + "`suplier`='"+jTextFieldSuplier.getText()+"' "
        + "WHERE `kode_barang`="+jTextFieldKodeBarang.getText();

        executeSQLQuery(query, "Updated");
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapus1ActionPerformed
        String query = "DELETE FROM `barang` WHERE kode_barang="+jTextFieldKodeBarang.getText();

        executeSQLQuery(query, "Deleted");
    }//GEN-LAST:event_jButtonHapus1ActionPerformed

    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
//        String tanggal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
//        //System.out.println(tanggal);
//
//        String kodeBarang = jTextFieldNamaBarang.getText();
//        String namaBarang = jTextFieldNamaBarang.getText();
//        int kandunganNikotin = Integer.parseInt(jTextFieldKandunganNikotin.getText());
//        int typeBarang = Integer.parseInt((String)cbTypeBarang.getSelectedItem());
//        double hargaJual = Double.parseDouble(jTextFieldHargaJual.getText());
//        double hargaBeli = Double.parseDouble(jTextFieldHargaBeli.getText());
//        int stok = Integer.parseInt(jTextFieldQty.getText());
//        String suplier = jTextFieldSuplier.getText();
//        //        String jenisBayar = "Cash";
//        int id_pengguna=101;
//
//        String query = "INSERT INTO `penjualan_header`(`kode_barang`,`tanggal`, `nama_barang`, `kandungan_nikotin`, `id_type`, `harga_jual`, `harga_beli`, `qty`, `suplier`, `id_pengguna`) "
//        + "VALUES ('"+kodeBarang+"','"+tanggal+"','"+namaBarang+"','"+typeBarang+"','"+hargaJual+"','"+hargaBeli+"','"+stok+"','"+suplier+"','"+id_pengguna+"')";
//
//        simpanTransaksi(query);
        Document doc = new Document();

        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if(saveFile != null){
//                saveFile = new File(saveFile.toString()+".pdf");
                PdfWriter.getInstance(doc, new FileOutputStream(new File(saveFile.toString()+".pdf")));

                doc.open();

                PdfPTable tabel = new PdfPTable(7);

                
                tabel.addCell("Kode Barang");
                tabel.addCell("Nama Barang");
                tabel.addCell("Kandungan NIkotin");
                tabel.addCell("Type Barang");
                tabel.addCell("Harga Beli");
                tabel.addCell("Harga Jual");
                tabel.addCell("Qty");
                tabel.addCell("Supplier");
                for(int a=0 ; a<jTableBarangMasuk.getRowCount(); a++){
                    String kode = jTableBarangMasuk.getValueAt(a, 0).toString();
                    String nama = jTableBarangMasuk.getValueAt(a, 1).toString();
                    String nikotin = jTableBarangMasuk.getValueAt(a, 2).toString();
                    String type = jTableBarangMasuk.getValueAt(a, 3).toString();
                    String hBeli = jTableBarangMasuk.getValueAt(a, 4).toString();
                    String hJual = jTableBarangMasuk.getValueAt(a, 5).toString();
                    String qty = jTableBarangMasuk.getValueAt(a, 6).toString();
                    String supplier = jTableBarangMasuk.getValueAt(a, 7).toString();

                    tabel.addCell(kode);
                    tabel.addCell(nama);
                    tabel.addCell(nikotin);
                    tabel.addCell(type);
                    tabel.addCell(hBeli);
                    tabel.addCell(hJual);
                    tabel.addCell(qty);
                    tabel.addCell(supplier);
                }
                doc.add(tabel);

                JOptionPane.showMessageDialog(null, "DOWNLOAD SUKSES", "DOWNLOAD PDF", JOptionPane.PLAIN_MESSAGE);
                openFile(saveFile.toString()+".pdf");
//                openFile(saveFile.toString());
            }else{
                JOptionPane.showMessageDialog(null,"SILAHKAN ISI NAMA FILE");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(kelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(kelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        doc.close();
        
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jTextFieldSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSuplierActionPerformed

    private void jTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyActionPerformed

    private void jTextFieldHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaJualActionPerformed

    private void jTextFieldHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaBeliActionPerformed

    private void jTableBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMasukMouseClicked
        jTextFieldKodeBarang.setEditable(false);
              
        //menampilkan data yang di klik pada table ke dalam form      
        
        int i = jTableBarangMasuk.getSelectedRow();
        
        TableModel model = jTableBarangMasuk.getModel();
        
        jTextFieldKodeBarang.setText(model.getValueAt(i, 0).toString());
        jTextFieldNamaBarang.setText(model.getValueAt(i, 1).toString());
        jTextFieldKandunganNikotin.setText(model.getValueAt(i, 2).toString());
        cbTypeBarang.getModel().setSelectedItem("PCS");
        jTextFieldHargaJual.setText(model.getValueAt(i, 4).toString());
        jTextFieldHargaBeli.setText(model.getValueAt(i, 5).toString());
        jTextFieldQty.setText(model.getValueAt(i, 6).toString());
        jTextFieldSuplier.setText(model.getValueAt(i, 7).toString());
    }//GEN-LAST:event_jTableBarangMasukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTypeBarang;
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus1;
    private javax.swing.JButton jButtonTambah1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTypeBarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBarangMasuk;
    private javax.swing.JTextField jTextFieldHargaBeli;
    private javax.swing.JTextField jTextFieldHargaJual;
    private javax.swing.JTextField jTextFieldKandunganNikotin;
    private javax.swing.JTextField jTextFieldKodeBarang;
    private javax.swing.JTextField jTextFieldNamaBarang;
    private javax.swing.JTextField jTextFieldQty;
    private javax.swing.JTextField jTextFieldSuplier;
    // End of variables declaration//GEN-END:variables
}
