/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dashboard;

import database.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdul Latip Muhyi
 */
public class pMasterType extends javax.swing.JInternalFrame {

    /**
     * Creates new form pMasterType
     */
    public pMasterType() {
        initComponents();
        
        show_type_inJtable();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTypeBarang = new javax.swing.JLabel();
        tfTypeBarang = new javax.swing.JTextField();
        tfKeterangan = new javax.swing.JTextField();
        jButtonTambah1 = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMasterType = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Master Type");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabel2.setText("Type Barang");

        jLabelTypeBarang.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        jLabelTypeBarang.setText("Keterangan");

        tfKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKeteranganActionPerformed(evt);
            }
        });

        jButtonTambah1.setBackground(new java.awt.Color(102, 153, 255));
        jButtonTambah1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N
        jButtonTambah1.setText("Tambah");
        jButtonTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambah1ActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(102, 204, 0));
        jButtonEdit.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-making_notes.png"))); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonHapus1.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHapus1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        jButtonHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete_trash.png"))); // NOI18N
        jButtonHapus1.setText("Hapus");
        jButtonHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapus1ActionPerformed(evt);
            }
        });

        tMasterType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Type", "Type Barabg", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMasterType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMasterTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tMasterType);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTambah1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(tfTypeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTypeBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 544, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    koneksi k = new koneksi();
    Connection con = k.connection;
    
    public ArrayList<typeBarang> getTypeList()
    {
       ArrayList<typeBarang> typeList = new ArrayList<typeBarang>();
       
       String query = "SELECT * FROM type";
       
       Statement st;
       ResultSet rs;
       
       try{
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           typeBarang Type;           
           while(rs.next()){
               Type = new typeBarang(rs.getInt("id_type"),rs.getString("type_barang"), 
                       rs.getString("keterangan"));
               typeList.add(Type);
           }        
       }catch(Exception e){
           e.printStackTrace();
       }       
       return typeList;
    }
    
    public void show_type_inJtable(){
        
        ArrayList<typeBarang> list = getTypeList();
        
        DefaultTableModel model = (DefaultTableModel)tMasterType.getModel();
        
        Object[] row = new Object[3];
        
        for(int i=0; i < list.size(); i++){
            row[0] = list.get(i).getIdType();
            row[1] = list.get(i).getTypeBarang();
            row[2] = list.get(i).getKeterangan();
            
            model.addRow(row);
        }       
    }
    
    public void executeSQLQuery(String query, String pesan)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
               
               //refresh jtable data
               DefaultTableModel model = (DefaultTableModel)tMasterType.getModel();
               model.setRowCount(0);
               show_type_inJtable();
               
               JOptionPane.showMessageDialog(null, "Data " + pesan + " Succefully");
           }
           else{
               JOptionPane.showMessageDialog(null, "Data Not " + pesan);           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    public void simpanTransaksi(String query)
    {
        Statement st;
        
        try{
           st = con.createStatement();
           
           if(st.executeUpdate(query) == 1){
                                   
                int jawab;

                jawab = JOptionPane.showOptionDialog(null, "Cetak Faktur Penjualan?", "", 
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

                if(jawab == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(null, "Cetak Faktur !");
                }               
           }
           else{
               JOptionPane.showMessageDialog(null, "Transaksi tidak dapat disimpan");           
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    private void tfKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKeteranganActionPerformed

    private void jButtonTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambah1ActionPerformed
        String query = "INSERT INTO `type`(`type_barang`, `keterangan`) "
        + "VALUES ('"+tfTypeBarang.getText()+"','"+tfKeterangan.getText()+"')";

        executeSQLQuery(query, "Inserted");
    }//GEN-LAST:event_jButtonTambah1ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String query = "UPDATE `type` SET `type_barang`='"+tfTypeBarang.getText()+"',"
        + "`keterangan`='"+tfKeterangan.getText()+"',"
        + "WHERE `id_type`=";

        executeSQLQuery(query, "Updated");
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapus1ActionPerformed
        String query = "DELETE FROM `type` WHERE id_barang=";

        executeSQLQuery(query, "Deleted");
    }//GEN-LAST:event_jButtonHapus1ActionPerformed

    private void tMasterTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMasterTypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tMasterTypeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus1;
    private javax.swing.JButton jButtonTambah1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTypeBarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tMasterType;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfTypeBarang;
    // End of variables declaration//GEN-END:variables
}
